name: Create new release
on:
    push:
      branches: [ "master" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.actor != vars.RELEASE_ACTOR_NAME
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Get next release version
        run: |
            VER=$(awk -F '=' ' /^version/ { print $2 } ' gradle.properties)
            echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Publish package
        run: |
            git checkout -B "release-${{ env.VERSION }}"
            git config user.email ${{ vars.RELEASE_ACTOR_NAME }}@users.noreply.github.com
            git config user.name ${{ vars.RELEASE_ACTOR_NAME }}
            ./gradlew release -Prelease.useAutomaticVersion=true

      - name: Create pull request
        uses: repo-sync/pull-request@v2.12.1
        id: create-pr
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            source_branch: "release-${{ env.VERSION }}"
            pr_title: "Create new release: ${{ env.VERSION }}"
            pr_body: "Create release ${{ env.VERSION }} automatically."

      - name: Create GitHub release
        uses: actions/create-release@v1.1.4
        id: create-release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ env.VERSION }}
            release_name: quartz-mongodb v${{ env.VERSION }}
            draft: false
            body: |
                Usage:
                    `implementation("io.github.avi-sanwal:quartz-mongodb:${{ env.VERSION }}")`
